spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mercado_livro?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: '!@#Qwezx13'
    # Keep the connection alive if idle for a long time (needed in production)
    # testWhileIdle: true
    # alidationQuery: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
